title: Project
icon: tag
image:
  query: none
  back: "#ace6bc"
  color: "35b45e"


columns:
  - width: 2/3
    sections:
      campagin:
        type: pages
        headline: Campaigns
        template: campaign

  - width: 1/3
    sections:
      infoLeft:
        type: fields
        fields:
          showInPortfolio:
            label: Show "{{page.title}}" in Portfolio?
            type: toggle
            default: no
            text:
              - "No"
              - "Yes"
            options:
              - no
              - yes

          inDevelopment:
            label: In development
            type: toggle
            default: no
            text:
              - "No"
              - "Yes"
            options:
              - no
              - yes

          passwordInfo:
            type: info
            label: Need a password?
            text: >
              Use this <a href="https://www.dashlane.com/features/password-generator" target="_blank">password generator</a> to create a secure password and enter it in the field below.

          projectPassword:
            label: Password
            type: text
            width: 1/1
            required: true
          
          created:
            label: Creation Date
            type: date
            time: false
            width: 1/1
            type: hidden
